#include "map.h"
#include <cstdlib>  // for rand

std::vector<DIRECTION> Map::available_actions(int atstate) const {
  std::vector<DIRECTION> ret;
  for(int x = 8 ; x != 0 ; x >>= 1) {
    if(map[atstate] & x)
      ret.push_back((DIRECTION)x);
  };
//  if(atstate == goal)
//    ret.push_back(TELEPORT);
  return ret;
}

Map::Map() {
  //_moves = 0;
  //goal = 350;
  _width = 50;
  goal = std::rand() % (50*50);
  do {
    current_location = std::rand() % (50*50);
  } while(current_location == goal);
  map = {{RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT,RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,
  UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,DOWN,UP,UP,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP,
  UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT+DOWN,LEFT,UP,DOWN,UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP,UP,UP+DOWN,RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT,UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP,UP+RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,
  UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+DOWN,UP+DOWN,UP,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+DOWN,DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT,UP,DOWN,UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,DOWN,UP+DOWN,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+DOWN,DOWN,UP+RIGHT,LEFT,UP+RIGHT,LEFT,UP+DOWN,DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,
  UP+DOWN,UP,RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP,UP+DOWN,RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,
  UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP+DOWN,DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+RIGHT,LEFT,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,
  RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+UP+DOWN,RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP,UP+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT,
  UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,UP,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT,DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+UP+DOWN,DOWN,UP,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,RIGHT+DOWN,LEFT,DOWN,UP,UP+DOWN,DOWN,UP+DOWN,RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT,DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP,RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,
  UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,DOWN,RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+DOWN,RIGHT,LEFT+UP+DOWN,
  RIGHT+DOWN,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT,DOWN,UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+DOWN,UP,RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP,UP,UP+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,UP+RIGHT,LEFT,DOWN,UP+RIGHT+DOWN,LEFT+UP,DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,
  UP,UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT,UP,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,DOWN,UP+DOWN,UP,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+DOWN,UP,RIGHT+DOWN,LEFT+DOWN,
  DOWN,RIGHT,LEFT+UP,UP,UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,UP,UP+DOWN,RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,UP,UP+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT,DOWN,UP,DOWN,UP+DOWN,UP,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP+DOWN,
  UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT,RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT,DOWN,UP,UP,UP,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,DOWN,UP,RIGHT,LEFT+UP+RIGHT,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP,UP+DOWN,
  UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT,RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+DOWN,UP,DOWN,UP,UP,UP,UP,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,DOWN,UP,RIGHT,LEFT+UP,RIGHT,LEFT+UP+DOWN,
  RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP,DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT,LEFT+UP+RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP,DOWN,UP+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,
  UP,RIGHT+DOWN,LEFT+UP+DOWN,DOWN,UP+DOWN,UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP,UP+DOWN,DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT,RIGHT+DOWN,LEFT,UP,UP+DOWN,RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+UP,DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,UP,UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+DOWN,UP,UP+DOWN,
  DOWN,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT,UP+DOWN,DOWN,DOWN,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP,RIGHT,LEFT+UP+DOWN,
  UP+RIGHT+DOWN,LEFT+UP+DOWN,DOWN,DOWN,UP,DOWN,RIGHT,LEFT+UP+RIGHT,LEFT,UP,RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,DOWN,UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP,RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT,UP,UP+RIGHT+DOWN,LEFT,DOWN,UP,RIGHT+DOWN,LEFT,UP+DOWN,
  UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+UP,UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,
  UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,DOWN,UP,UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,DOWN,RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,
  UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP,UP+RIGHT+DOWN,LEFT+UP,DOWN,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+RIGHT,LEFT+DOWN,UP,UP+DOWN,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP,DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,
  UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+DOWN,
  RIGHT+DOWN,LEFT+UP+DOWN,UP,RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,DOWN,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP+DOWN,DOWN,UP,UP,UP+DOWN,
  UP+DOWN,UP,RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,DOWN,UP+RIGHT,LEFT+DOWN,UP,DOWN,DOWN,UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT+DOWN,LEFT,RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,DOWN,UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,
  UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP,UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+DOWN,DOWN,DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+DOWN,UP,
  RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,DOWN,UP,UP+DOWN,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP,RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP,UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+UP,UP+DOWN,DOWN,
  UP+DOWN,UP,UP,UP+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT,UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,DOWN,UP+RIGHT,LEFT,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT,UP+DOWN,UP+DOWN,DOWN,UP,UP,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT,DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT+UP,
  UP+RIGHT+DOWN,LEFT,RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT,UP,DOWN,RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT,RIGHT,LEFT+DOWN,UP+DOWN,UP,UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP,UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,
  UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP,RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+DOWN,UP,UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP,DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,
  DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP,UP,UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,DOWN,DOWN,UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,
  UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,DOWN,UP,RIGHT,LEFT+UP,DOWN,UP+RIGHT,LEFT,UP+RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT,RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT,UP+DOWN,DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP,
  UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,DOWN,DOWN,DOWN,UP,UP,DOWN,UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP,UP+DOWN,RIGHT,LEFT+RIGHT,LEFT+DOWN,DOWN,DOWN,
  UP+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP,DOWN,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,DOWN,UP,RIGHT,LEFT+UP+DOWN,UP+DOWN,DOWN,UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+UP+DOWN,UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,
  UP+RIGHT+DOWN,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,DOWN,UP,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP,
  UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP+DOWN,UP+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+DOWN,UP,UP+DOWN,DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP,DOWN,RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,
  UP+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+UP,DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+DOWN,DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT+DOWN,LEFT,DOWN,UP+DOWN,DOWN,UP+RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+UP,
  RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT,UP,DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT,UP+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+RIGHT+DOWN,LEFT,UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP,UP+DOWN,DOWN,UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,
  DOWN,DOWN,RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP,RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,UP+DOWN,UP,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+DOWN,DOWN,UP,RIGHT,LEFT+UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,
  UP+RIGHT,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP+DOWN,UP,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+DOWN,UP,UP+DOWN,UP,UP,UP+DOWN,UP+RIGHT,LEFT+DOWN,UP,UP+RIGHT+DOWN,LEFT+UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,
  RIGHT+DOWN,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT,DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP,UP,RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,DOWN,UP+RIGHT,LEFT,UP+DOWN,RIGHT+DOWN,LEFT+UP,UP,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP,
  UP,UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP,UP+RIGHT,LEFT+RIGHT,LEFT,RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+UP,RIGHT,LEFT+UP,RIGHT,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,
  RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+RIGHT+DOWN,LEFT,DOWN,RIGHT,LEFT+UP+DOWN,UP+DOWN,UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,
  UP+RIGHT,LEFT,UP,UP,UP+RIGHT,LEFT+DOWN,DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,DOWN,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+DOWN,
  RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,DOWN,DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP,RIGHT+DOWN,LEFT,DOWN,RIGHT+DOWN,LEFT+DOWN,DOWN,RIGHT+DOWN,LEFT+DOWN,DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP,UP+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP,DOWN,UP+DOWN,UP,UP+DOWN,UP,
  UP+DOWN,RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT,UP,DOWN,RIGHT,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+DOWN,RIGHT+DOWN,LEFT,UP+DOWN,UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+DOWN,
  UP+DOWN,DOWN,UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,DOWN,UP+RIGHT+DOWN,LEFT+DOWN,UP+DOWN,RIGHT,LEFT+UP+DOWN,UP+DOWN,UP,RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP,UP,UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,DOWN,RIGHT,LEFT+UP,
  UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT,LEFT,UP+DOWN,UP,UP,UP+DOWN,UP+RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,RIGHT,LEFT+UP+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT+DOWN,LEFT+UP,UP,UP+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT,RIGHT+DOWN,LEFT+UP,DOWN,DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+DOWN,UP+DOWN,UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,
  DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,UP,UP+RIGHT,LEFT+UP,RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+DOWN,RIGHT,LEFT+UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT,UP+RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+DOWN,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,RIGHT+DOWN,LEFT+DOWN,
  UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+UP,UP,RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+UP,UP+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT,DOWN,UP+DOWN,RIGHT,LEFT+UP+DOWN,DOWN,UP+RIGHT,LEFT+UP,UP,UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP,UP+DOWN,UP,RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+DOWN,RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,DOWN,UP+DOWN,DOWN,UP,UP+DOWN,
  RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT,UP+RIGHT,LEFT,UP+RIGHT,LEFT+UP+RIGHT,LEFT,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT,RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+UP,
  }};
  /*
  current_location = 0;
  goal = 18*18-1;
  _width = 18;
  map = {{
  RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+DOWN,
  UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT,UP+RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,
  UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+UP+RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,
  RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP,UP+DOWN,UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+DOWN,
  UP+RIGHT,LEFT+DOWN,DOWN,RIGHT+DOWN,LEFT+UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,
  RIGHT+DOWN,UP+LEFT+DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,
  UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT,UP+DOWN,
  UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,
  UP+DOWN,RIGHT+DOWN,LEFT+DOWN,RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,
  UP+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,RIGHT,LEFT+UP,UP+DOWN,UP+DOWN,UP+DOWN,UP,
  RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+UP+RIGHT+DOWN,LEFT,UP+RIGHT,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+DOWN,
  UP+DOWN,UP+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,
  UP+DOWN,UP+RIGHT,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT+DOWN,UP+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT+DOWN,LEFT+UP,UP+DOWN,RIGHT+DOWN,LEFT+UP,DOWN,
  UP+RIGHT,LEFT+RIGHT,LEFT+DOWN,UP+DOWN,UP+DOWN,UP,UP+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT+UP,UP,RIGHT+DOWN,LEFT+UP+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+UP+DOWN,
  RIGHT+DOWN,LEFT+DOWN,UP+DOWN,UP+DOWN,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP,RIGHT+DOWN,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT+DOWN,LEFT,UP+DOWN,
  UP+DOWN,UP+RIGHT+DOWN,LEFT+UP,UP+RIGHT,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+DOWN,RIGHT+DOWN,LEFT+RIGHT,LEFT+UP,RIGHT+DOWN,LEFT+UP,
  UP+DOWN,UP,RIGHT+DOWN,LEFT+DOWN,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT+DOWN,LEFT+DOWN,UP+RIGHT+DOWN,LEFT+UP,RIGHT+DOWN,LEFT+UP,UP+DOWN,UP+RIGHT,LEFT+DOWN,RIGHT+DOWN,LEFT+UP,DOWN,
  UP+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+UP,RIGHT,LEFT+UP+RIGHT,LEFT,UP+RIGHT,LEFT+RIGHT,LEFT+UP,UP+RIGHT,LEFT+RIGHT,LEFT+UP
  }};
  */
}

int Map::move(DIRECTION _move) {
  if(_move == TELEPORT && current_location == goal) {
    current_location = std::rand() % (50*50);
    return current_location;
  };
  switch(map[current_location] & _move) {
    case STOP:
      throw "Invalid move";
    case UP:
      current_location -= _width;
      break;
    case DOWN:
      current_location += _width;
      break;
    case LEFT:
      current_location -= 1;
      break;
    case RIGHT:
      current_location += 1;
      break;
  };
  //_moves++;
  return current_location;
};

/*
int Map::tostate(int fromstate, DIRECTION _move) {
  switch(map[fromstate] & _move) {
    case STOP:
      throw "Invalid move";
    case UP:
      fromstate -= _width;
      break;
    case DOWN:
      fromstate += _width;
      break;
    case LEFT:
      fromstate -= 1;
      break;
    case RIGHT:
      fromstate += 1;
      break;
  };
  return fromstate;
};

NodeMap Map::generate_scores()
{
   NodeMap nm;
   std::vector<int> visited;
   generate_scores(&visited, &nm, goal, 0);
   return nm;
}

void Map::generate_scores(std::vector<int> *visited, NodeMap *nm, int state, int score)
{
  if(std::find(visited->begin(), visited->end(), state) != visited->end()) return;
  visited->push_back(state);
  //
  // Add it to the map if it doesn't exist
  //
  if(nm->find(state) == nm->end())
    nm->emplace(state, Node(_width, state, std::numeric_limits<int>::max(), available_actions(state)));

  //
  // Set the minimum number of moves to the goal
  //
  if(nm->at(state).cost() > score)
    nm->at(state).cost(score);
  //
  // Walk depth first in each direction, adding to the number of moves it takes
  // to reach the goal
  //
  for(DIRECTION d : available_actions(state))
    generate_scores(visited, nm, tostate(state, d), score+1);

  visited->pop_back();
}
*/
